import type { OperationType, PropertyType } from "../../src/generated/prisma/enums";

export type SeedProperty = {
  /** Fixed identifier so the seed can be re-run without duplicating rows. */
  id: string;
  title: string;
  description: string;
  operationType: OperationType;
  propertyType: PropertyType;
  /** USD. Sale: total price. Rent: monthly price. */
  price: string;
  usableArea?: string;
  totalArea?: string;
  bedrooms?: number;
  bathrooms?: number;
  parkingSpaces?: number;
  ageInYears?: number;
  address: string;
  commune: string;
  city: string;
  region: string;
  isPublished: boolean;
  isFeatured: boolean;
  createdAt: string;
  featureNames: string[];
};

export const seedFeatureNames = [
  "Piscina",
  "Gimnasio",
  "Quincho",
  "Lavandería",
  "Jardín",
  "Terraza",
  "Bodega",
  "Ascensor",
  "Conserjería",
  "Seguridad",
  "Calefacción",
  "Aire acondicionado",
  "Pet friendly",
] as const;

const seedPropertyId = (sequence: number) =>
  `5eed0000-0000-4000-8000-${sequence.toString().padStart(12, "0")}`;

const METROPOLITANA = "Región Metropolitana";
const VALPARAISO = "Región de Valparaíso";

export const seedProperties: SeedProperty[] = [
  {
    id: seedPropertyId(1),
    title: "Casa mediterránea con piscina en La Dehesa",
    description:
      "Amplia casa de dos pisos en condominio cerrado, con living de doble altura, cocina equipada con isla, sala de estar y dormitorio principal en suite con walk-in closet. Jardín consolidado, piscina temperada y quincho techado.",
    operationType: "SALE",
    propertyType: "HOUSE",
    price: "890000",
    usableArea: "320",
    totalArea: "650",
    bedrooms: 5,
    bathrooms: 4,
    parkingSpaces: 3,
    ageInYears: 8,
    address: "Camino Los Trapenses 4200",
    commune: "Lo Barnechea",
    city: "Santiago",
    region: METROPOLITANA,
    isPublished: true,
    isFeatured: true,
    createdAt: "2026-09-20T12:00:00.000Z",
    featureNames: ["Piscina", "Jardín", "Quincho", "Seguridad", "Calefacción"],
  },
  {
    id: seedPropertyId(2),
    title: "Departamento luminoso a pasos del Metro Pedro de Valdivia",
    description:
      "Departamento de dos dormitorios con orientación nororiente, living comedor con salida a terraza y cocina integrada. Edificio con conserjería 24 horas, gimnasio y bodega incluida.",
    operationType: "SALE",
    propertyType: "APARTMENT",
    price: "215000",
    usableArea: "68",
    totalArea: "75",
    bedrooms: 2,
    bathrooms: 2,
    parkingSpaces: 1,
    ageInYears: 5,
    address: "Av. Nueva Providencia 1860",
    commune: "Providencia",
    city: "Santiago",
    region: METROPOLITANA,
    isPublished: true,
    isFeatured: true,
    createdAt: "2026-09-18T12:00:00.000Z",
    featureNames: ["Ascensor", "Conserjería", "Bodega", "Gimnasio", "Terraza"],
  },
  {
    id: seedPropertyId(3),
    title: "Departamento familiar en arriendo frente a Apoquindo",
    description:
      "Tres dormitorios, dos baños y amplia terraza con vista despejada a la cordillera. Cocina independiente con logia, calefacción central y dos estacionamientos subterráneos.",
    operationType: "RENT",
    propertyType: "APARTMENT",
    price: "1450",
    usableArea: "95",
    totalArea: "105",
    bedrooms: 3,
    bathrooms: 2,
    parkingSpaces: 2,
    ageInYears: 10,
    address: "Av. Apoquindo 3000",
    commune: "Las Condes",
    city: "Santiago",
    region: METROPOLITANA,
    isPublished: true,
    isFeatured: true,
    createdAt: "2026-09-16T12:00:00.000Z",
    featureNames: ["Ascensor", "Conserjería", "Calefacción", "Terraza", "Bodega"],
  },
  {
    id: seedPropertyId(4),
    title: "Estudio moderno en arriendo cerca de Plaza Ñuñoa",
    description:
      "Departamento de un ambiente con cocina americana y closet empotrado, ideal para estudiantes o profesionales. Edificio nuevo con lavandería, gimnasio y sala cowork. Se aceptan mascotas.",
    operationType: "RENT",
    propertyType: "APARTMENT",
    price: "520",
    usableArea: "32",
    totalArea: "35",
    bedrooms: 1,
    bathrooms: 1,
    parkingSpaces: 0,
    ageInYears: 3,
    address: "Av. Irarrázaval 3450",
    commune: "Ñuñoa",
    city: "Santiago",
    region: METROPOLITANA,
    isPublished: true,
    isFeatured: false,
    createdAt: "2026-09-14T12:00:00.000Z",
    featureNames: ["Pet friendly", "Lavandería", "Gimnasio", "Ascensor"],
  },
  {
    id: seedPropertyId(5),
    title: "Casa tradicional con amplio jardín en Ñuñoa",
    description:
      "Casa de un piso en barrio residencial, con cuatro dormitorios, tres baños, living y comedor separados y cocina con comedor de diario. Patio con árboles frutales y quincho.",
    operationType: "SALE",
    propertyType: "HOUSE",
    price: "385000",
    usableArea: "140",
    totalArea: "280",
    bedrooms: 4,
    bathrooms: 3,
    parkingSpaces: 2,
    ageInYears: 25,
    address: "Dublé Almeyda 2750",
    commune: "Ñuñoa",
    city: "Santiago",
    region: METROPOLITANA,
    isPublished: true,
    isFeatured: false,
    createdAt: "2026-09-12T12:00:00.000Z",
    featureNames: ["Jardín", "Quincho", "Calefacción"],
  },
  {
    id: seedPropertyId(6),
    title: "Oficina corporativa en arriendo en barrio El Golf",
    description:
      "Planta libre habilitada con recepción, dos salas de reuniones, privados y kitchenette. Edificio clase A con control de acceso, climatización central y cuatro estacionamientos.",
    operationType: "RENT",
    propertyType: "OFFICE",
    price: "2800",
    usableArea: "180",
    totalArea: "180",
    bathrooms: 2,
    parkingSpaces: 4,
    ageInYears: 12,
    address: "Av. Isidora Goyenechea 2900",
    commune: "Las Condes",
    city: "Santiago",
    region: METROPOLITANA,
    isPublished: true,
    isFeatured: false,
    createdAt: "2026-09-10T12:00:00.000Z",
    featureNames: ["Aire acondicionado", "Ascensor", "Seguridad", "Conserjería"],
  },
  {
    id: seedPropertyId(7),
    title: "Oficina en venta a pasos del Metro Los Leones",
    description:
      "Oficina con tres privados, sala de reuniones y baño interior. Excelente conectividad, locomoción a la puerta y un estacionamiento. Ideal para consulta o estudio profesional.",
    operationType: "SALE",
    propertyType: "OFFICE",
    price: "198000",
    usableArea: "75",
    totalArea: "75",
    bathrooms: 1,
    parkingSpaces: 1,
    ageInYears: 15,
    address: "Av. Providencia 2330",
    commune: "Providencia",
    city: "Santiago",
    region: METROPOLITANA,
    isPublished: true,
    isFeatured: false,
    createdAt: "2026-09-08T12:00:00.000Z",
    featureNames: ["Ascensor", "Conserjería", "Aire acondicionado"],
  },
  {
    id: seedPropertyId(8),
    title: "Terreno plano en condominio de Chicureo",
    description:
      "Sitio de 5.000 m² con factibilidad de agua y luz, en condominio con acceso controlado y urbanización subterránea. Vista despejada a los cerros y cercanía a colegios.",
    operationType: "SALE",
    propertyType: "LAND",
    price: "260000",
    totalArea: "5000",
    address: "Camino Chicureo km 6",
    commune: "Colina",
    city: "Colina",
    region: METROPOLITANA,
    isPublished: true,
    isFeatured: false,
    createdAt: "2026-09-06T12:00:00.000Z",
    featureNames: ["Seguridad"],
  },
  {
    id: seedPropertyId(9),
    title: "Parcela con vista al lago Llanquihue",
    description:
      "Parcela de una hectárea con vista al lago y a los volcanes Osorno y Calbuco. Camino interior estabilizado, rol propio y bosque nativo. A quince minutos del centro de Puerto Varas.",
    operationType: "SALE",
    propertyType: "LAND",
    price: "145000",
    totalArea: "10000",
    address: "Ruta 225 km 12",
    commune: "Puerto Varas",
    city: "Puerto Varas",
    region: "Región de Los Lagos",
    isPublished: true,
    isFeatured: true,
    createdAt: "2026-09-04T12:00:00.000Z",
    featureNames: [],
  },
  {
    id: seedPropertyId(10),
    title: "Casa en arriendo con vista al mar en Reñaca",
    description:
      "Casa de tres niveles con terrazas panorámicas, cuatro dormitorios y sala de estar. Piscina, jardín en desnivel y estacionamiento para dos vehículos. A cinco minutos de la playa.",
    operationType: "RENT",
    propertyType: "HOUSE",
    price: "1900",
    usableArea: "210",
    totalArea: "400",
    bedrooms: 4,
    bathrooms: 3,
    parkingSpaces: 2,
    ageInYears: 12,
    address: "Av. Borgoño 15200",
    commune: "Viña del Mar",
    city: "Viña del Mar",
    region: VALPARAISO,
    isPublished: true,
    isFeatured: false,
    createdAt: "2026-09-02T12:00:00.000Z",
    featureNames: ["Piscina", "Terraza", "Jardín"],
  },
  {
    id: seedPropertyId(11),
    title: "Departamento nuevo en primera línea en Concón",
    description:
      "Tres dormitorios, dos baños y terraza corrida con vista frontal al océano. Terminaciones de primer nivel, ventanas termopanel y edificio con piscina y gimnasio.",
    operationType: "SALE",
    propertyType: "APARTMENT",
    price: "310000",
    usableArea: "110",
    totalArea: "135",
    bedrooms: 3,
    bathrooms: 2,
    parkingSpaces: 2,
    ageInYears: 2,
    address: "Av. Borgoño 23500",
    commune: "Concón",
    city: "Concón",
    region: VALPARAISO,
    isPublished: true,
    isFeatured: true,
    createdAt: "2026-08-31T12:00:00.000Z",
    featureNames: ["Piscina", "Gimnasio", "Terraza", "Ascensor", "Conserjería"],
  },
  {
    id: seedPropertyId(12),
    title: "Departamento patrimonial en arriendo en Cerro Alegre",
    description:
      "Departamento remodelado en casona patrimonial, con techos altos, pisos de madera y terraza con vista a la bahía. Rodeado de cafés, galerías y ascensores históricos.",
    operationType: "RENT",
    propertyType: "APARTMENT",
    price: "680",
    usableArea: "70",
    totalArea: "70",
    bedrooms: 2,
    bathrooms: 1,
    parkingSpaces: 0,
    ageInYears: 60,
    address: "Lautaro Rosas 540",
    commune: "Valparaíso",
    city: "Valparaíso",
    region: VALPARAISO,
    isPublished: true,
    isFeatured: false,
    createdAt: "2026-08-29T12:00:00.000Z",
    featureNames: ["Terraza", "Pet friendly"],
  },
  {
    id: seedPropertyId(13),
    title: "Casa en condominio en San Pedro de la Paz",
    description:
      "Casa de dos pisos con cuatro dormitorios, tres baños y sala de estar en segundo piso. Patio amplio con quincho, calefacción a pellet y dos estacionamientos techados.",
    operationType: "SALE",
    propertyType: "HOUSE",
    price: "245000",
    usableArea: "160",
    totalArea: "350",
    bedrooms: 4,
    bathrooms: 3,
    parkingSpaces: 2,
    ageInYears: 7,
    address: "Av. Andalué 1850",
    commune: "San Pedro de la Paz",
    city: "Concepción",
    region: "Región del Biobío",
    isPublished: true,
    isFeatured: false,
    createdAt: "2026-08-27T12:00:00.000Z",
    featureNames: ["Jardín", "Quincho", "Calefacción", "Seguridad"],
  },
  {
    id: seedPropertyId(14),
    title: "Local comercial en arriendo en pleno centro de Santiago",
    description:
      "Local a la calle con amplia vitrina, altillo para bodega y baño. Alto flujo peatonal, a una cuadra de Plaza de Armas. Apto para retail o servicios.",
    operationType: "RENT",
    propertyType: "COMMERCIAL",
    price: "1600",
    usableArea: "90",
    totalArea: "90",
    bathrooms: 1,
    ageInYears: 20,
    address: "Paseo Ahumada 254",
    commune: "Santiago",
    city: "Santiago",
    region: METROPOLITANA,
    isPublished: true,
    isFeatured: false,
    createdAt: "2026-08-25T12:00:00.000Z",
    featureNames: ["Seguridad", "Bodega"],
  },
  {
    id: seedPropertyId(15),
    title: "Departamento cerca de la Avenida del Mar en La Serena",
    description:
      "Dos dormitorios y dos baños, con terraza y vista parcial al mar. Condominio con piscina, lavandería y áreas verdes. Excelente opción para inversión o segunda vivienda.",
    operationType: "SALE",
    propertyType: "APARTMENT",
    price: "128000",
    usableArea: "58",
    totalArea: "66",
    bedrooms: 2,
    bathrooms: 2,
    parkingSpaces: 1,
    ageInYears: 4,
    address: "Av. Pacífico 2100",
    commune: "La Serena",
    city: "La Serena",
    region: "Región de Coquimbo",
    isPublished: true,
    isFeatured: false,
    createdAt: "2026-08-23T12:00:00.000Z",
    featureNames: ["Piscina", "Lavandería", "Terraza", "Ascensor"],
  },
  {
    id: seedPropertyId(16),
    title: "Departamento de categoría en arriendo en Vitacura",
    description:
      "Tres dormitorios en suite, escritorio y amplia terraza con parrilla. Piso alto, climatización por recinto y dos estacionamientos más bodega. Edificio con piscina y seguridad 24/7.",
    operationType: "RENT",
    propertyType: "APARTMENT",
    price: "2300",
    usableArea: "150",
    totalArea: "170",
    bedrooms: 3,
    bathrooms: 3,
    parkingSpaces: 2,
    ageInYears: 6,
    address: "Av. Vitacura 5250",
    commune: "Vitacura",
    city: "Santiago",
    region: METROPOLITANA,
    isPublished: true,
    isFeatured: true,
    createdAt: "2026-08-21T12:00:00.000Z",
    featureNames: ["Piscina", "Seguridad", "Aire acondicionado", "Terraza", "Bodega", "Ascensor"],
  },
  {
    id: seedPropertyId(17),
    title: "Casa pareada cerca del Metro Plaza de Maipú",
    description:
      "Casa de dos pisos con tres dormitorios, dos baños y patio con espacio para ampliación. Barrio consolidado, cerca de colegios, supermercados y estación de Metro.",
    operationType: "SALE",
    propertyType: "HOUSE",
    price: "165000",
    usableArea: "95",
    totalArea: "160",
    bedrooms: 3,
    bathrooms: 2,
    parkingSpaces: 1,
    ageInYears: 18,
    address: "Av. Pajaritos 3100",
    commune: "Maipú",
    city: "Santiago",
    region: METROPOLITANA,
    isPublished: true,
    isFeatured: false,
    createdAt: "2026-08-19T12:00:00.000Z",
    featureNames: ["Jardín"],
  },
  {
    id: seedPropertyId(18),
    title: "Oficina equipada en arriendo en el centro de Viña del Mar",
    description:
      "Oficina amoblada con dos puestos de trabajo, sala de reuniones compartida y baño. Edificio con conserjería y ascensor, a pasos de Avenida Libertad.",
    operationType: "RENT",
    propertyType: "OFFICE",
    price: "750",
    usableArea: "45",
    totalArea: "45",
    bathrooms: 1,
    parkingSpaces: 0,
    ageInYears: 9,
    address: "Av. Libertad 798",
    commune: "Viña del Mar",
    city: "Viña del Mar",
    region: VALPARAISO,
    isPublished: true,
    isFeatured: false,
    createdAt: "2026-08-17T12:00:00.000Z",
    featureNames: ["Ascensor", "Conserjería", "Aire acondicionado"],
  },
  {
    // Draft: lets development verify that unpublished properties stay hidden.
    id: seedPropertyId(19),
    title: "Casa de montaña camino al volcán en Pucón (borrador)",
    description:
      "Casa de estilo sureño con estructura de madera nativa, cuatro dormitorios y gran terraza. Publicación en preparación: faltan fotografías y revisión de antecedentes.",
    operationType: "SALE",
    propertyType: "HOUSE",
    price: "420000",
    usableArea: "190",
    totalArea: "2500",
    bedrooms: 4,
    bathrooms: 3,
    parkingSpaces: 3,
    ageInYears: 11,
    address: "Camino al Volcán km 5",
    commune: "Pucón",
    city: "Pucón",
    region: "Región de La Araucanía",
    isPublished: false,
    isFeatured: false,
    createdAt: "2026-08-15T12:00:00.000Z",
    featureNames: ["Calefacción", "Terraza", "Jardín"],
  },
];
